In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
!pip install catboost
!pip install impyute
!pip install optuna
!pip install category_encoders

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 76.6 MB 163 kB/s 
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 308 kB 31.2 MB/s 
     |████████████████████████████████| 81 kB 11.8 MB/s 
     |████████████████████████████████| 209 kB 85.6 MB/s 
     |████████████████████████████████| 78 kB 8.2 MB/s 
     |████████████████████████████████| 146 kB 82.1 MB/s 
     |████████████████████████████████| 49 kB 7.4 MB/s 
     |████████████████████████████████| 112 kB 95.1 MB/s 
  Created wheel for pyperclip: filename=pyperclip-1.8.2-py3-none-any.whl size=11137 sha256=e8412116859ae65e617cd12a1f6c059eee9afd4dccf17e69a71c5ae48dd8160b
  Stored in directory: /root/.cache/pip/wheels/9f/18/84/8f69f8b08169c7bae2dde6bd7daf0c19

In [ ]:
# package를 import 하는 방식으로 바꾸는게 좋다!!

# Data Wrangling
import pandas as pd
from pandas import Series, DataFrame
import numpy as np

# Visualization
import matplotlib.pylab as plt
from matplotlib import font_manager, rc
import seaborn as sns
%matplotlib inline

# Preprocessing & Feature Engineering
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.impute import SimpleImputer 
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import PowerTransformer
from sklearn.preprocessing import Normalizer
from sklearn.preprocessing import RobustScaler
from sklearn.preprocessing import MaxAbsScaler
from sklearn.feature_selection import SelectPercentile
from impyute.imputation.cs import fast_knn
from sklearn.utils import all_estimators
from sklearn.metrics import r2_score,mean_squared_error
# from pycaret.classification import *

# Encoder

import category_encoders as ce
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
# Hyperparameter Optimization
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import RandomizedSearchCV

# Modeling
from sklearn.dummy import DummyClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.svm import SVC
from sklearn.ensemble import VotingClassifier
from sklearn.ensemble import StackingClassifier
from sklearn.base import ClassifierMixin
from catboost import CatBoostClassifier
from lightgbm import LGBMClassifier
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
import optuna
from sklearn import ensemble
from sklearn import metrics
from sklearn import model_selection
# Evaluation
from sklearn.metrics import roc_auc_score
from sklearn.metrics import accuracy_score
from sklearn.model_selection import cross_val_score

# Utility
import os
import time
import random
import warnings; warnings.filterwarnings("ignore")
from IPython.display import Image
import pickle
from tqdm import tqdm, tqdm_notebook
import platform
from itertools import combinations
from scipy.stats.mstats import gmean

#matplotlib 한글깨짐 지원
import platform

path = "c:/Windows/Fonts/malgun.ttf"
if platform.system() == 'Darwin':
    rc('font', family='AppleGothic')
elif platform.system() == 'Windows':
    font_name = font_manager.FontProperties(fname=path).get_name()
    rc('font', family=font_name)
else:
    print('Unknown system...')
rc('axes', unicode_minus=False) 

/usr/local/lib/python3.7/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


Unknown system...


### 1. 데이터불러오기

In [ ]:
ID_train = pd.DataFrame({'custid': pd.read_csv('/content/drive/MyDrive/머러컴피티션/X_train.csv', encoding='cp949').custid})
ID_test = pd.DataFrame({'custid': pd.read_csv('/content/drive/MyDrive/머러컴피티션/X_test.csv', encoding='cp949').custid})
target = pd.read_csv('/content/drive/MyDrive/머러컴피티션/y_train.csv', encoding = "cp949").group

In [ ]:
train = pd.read_csv('/content/drive/MyDrive/머러컴피티션/2등cat/snd_sum_shap_0615.csv')
test = pd.read_csv('/content/drive/MyDrive/머러컴피티션/2등cat/snd_sum_shap_te_0615.csv')

FileNotFoundError: ignored

In [ ]:
cat = pd.read_csv('/content/drive/MyDrive/머러컴피티션/2등cat/catboost용cat피처_train.csv',encoding='cp949')
cat_te = pd.read_csv('/content/drive/MyDrive/머러컴피티션/2등cat/catboost용cat피처_test.csv',encoding='cp949')

In [ ]:
test

Unnamed: 0     012.1       012   str_num  buyer_nm_2     143_y  \
0               0  0.258814 -0.350543  1.098612   -0.037479  0.013175   
1               1  0.258952 -0.334183  1.098612   -0.066326  0.003634   
2               2  0.261797  0.228570  0.693147   -0.074574 -0.017231   
3               3  0.258714 -0.382615  0.693147    0.029199 -0.055505   
4               4  0.258865 -0.336342  1.098612   -0.051324  0.020114   
...           ...       ...       ...       ...         ...       ...   
14375       14375  0.272532  2.383316  0.693147    0.222286 -0.000396   
14376       14376  0.258904 -0.344992  0.693147    0.029199  0.080320   
14377       14377  0.259843 -0.191469  0.693147   -0.015575  0.026705   
14378       14378  0.277271  3.311014  0.693147    0.180373 -0.007550   
14379       14379  0.258373 -0.421810  1.098612   -0.151650  0.034629   

           0602   pc_nm_1  mean_dis      96.2  ...     282_x      76_x  \
0     -0.602350 -0.048145  0.027055 -0.087500  ... -0.000414  0.016159   
1      1.495271  0.019834  0.033396 -0.077695  ... -0.027751  0.016302   
2      0.248037 -0.031968  0.024517 -0.124858  ...  0.034626  0.004518   
3     -0.772427  0.012990  0.050000 -0.305641  ... -0.070115  0.008007   
4     -0.659042 -0.014399  0.033333 -0.213799  ...  0.024747  0.038971   
...         ...       ...       ...       ...  ...       ...       ...   
14375 -0.772427 -0.036214  0.050000  0.016126  ... -0.048164  0.015755   
14376 -0.715735  0.012990  0.050000 -0.272694  ... -0.084702  0.082930   
14377 -0.772427 -0.023676  0.050000 -0.099931  ... -0.049353  0.068353   
14378 -0.715735  0.139536  0.012500  0.100161  ... -0.009873 -0.017650   
14379 -0.715735 -0.047074  0.033333 -0.214382  ... -0.017743  0.042565   

           25.2    비비안스타킹       레지나      16_x     262_y     총쇼핑시간  \
0      0.075577 -0.173885 -0.052019  0.018898 -0.015519  0.043472   
1      0.046212 -0.173885 -0.052019  0.070256  0.012450  2.072007   
2      0.207236 -0.173885 -0.052019  0.046709 -0.020829  0.616602   
3      0.051026 -0.173885 -0.052019  0.088692  0.081355 -0.843760   
4      0.149300 -0.173885 -0.052019  0.108686  0.023311 -0.669813   
...         ...       ...       ...       ...       ...       ...   
14375  0.137767 -0.173885 -0.052019  0.035975  0.024399 -0.772905   
14376  0.103517 -0.173885 -0.052019  0.125302 -0.002994 -0.851536   
14377  0.018465 -0.173885 -0.052019  0.071177  0.010930 -0.809742   
14378  0.139359 -0.173885 -0.052019  0.017315  0.019764 -0.744621   
14379  0.024130 -0.173885 -0.052019  0.067850  0.010019 -0.779644   

       part_pc_size_abbd_vegetable      17.3  
0                              0.0 -0.008342  
1                              0.0 -0.062874  
2                              1.0  0.019322  
3                              0.0 -0.029089  
4                              0.0  0.029067  
...                            ...       ...  
14375                          0.0  0.080027  
14376                          0.0  0.016099  
14377                          0.0 -0.053023  
14378                          0.0 -0.058787  
14379                          0.0  0.008807  

[14380 rows x 1353 columns]

In [ ]:
# 학습데이터

In [ ]:
test

012   str_num      25.3  buyer_nm_2   pc_nm_1      0602     143_y  \
0     -0.367196  0.532996  0.103666   -0.334814 -0.584096 -0.603846  0.022300   
1     -0.348065  0.532996  0.012933   -0.613327  0.346397  1.498119 -0.006187   
2      0.229543 -0.895276  0.019884   -0.691499 -0.369255  0.248302 -0.010585   
3     -0.397643 -0.895276  0.010798    0.340557  0.249467 -0.774276 -0.039801   
4     -0.357508  0.532996  0.127960   -0.469486 -0.130971 -0.660656  0.005785   
...         ...       ...       ...         ...       ...       ...       ...   
14375  2.448132 -0.895276 -0.153126    2.570589 -0.426225 -0.774276  0.015932   
14376 -0.358565 -0.895276  0.137584    0.340557  0.249467 -0.717466  0.077745   
14377 -0.194687 -0.895276  0.058507   -0.117902 -0.256481 -0.774276  0.027853   
14378  3.438691 -0.895276 -0.204604    2.049281  2.146916 -0.717466 -0.006178   
14379 -0.438351  0.532996  0.052316   -1.391620 -0.568816 -0.717466  0.026238   

           98.2    63.1.1     226_y  ...    베이비퀴즈        63      35.2  \
0      0.071966 -0.171161  0.037737  ... -0.04763 -0.025241  0.195811   
1      0.035340 -0.084821  0.001426  ... -0.04763 -0.067794  0.131288   
2      0.051159 -0.134624  0.019961  ... -0.04763  0.050950  0.190063   
3      0.055915 -0.069797  0.067967  ... -0.04763 -0.086005  0.202563   
4     -0.014172 -0.034720 -0.002600  ... -0.04763 -0.046897  0.157915   
...         ...       ...       ...  ...      ...       ...       ...   
14375  0.014452 -0.045184 -0.019401  ... -0.04763 -0.043816  0.181157   
14376  0.034472 -0.005619  0.068456  ... -0.04763 -0.118797  0.089612   
14377  0.109302 -0.190131 -0.043684  ... -0.04763 -0.060600  0.282389   
14378  0.027739 -0.217372  0.021470  ... -0.04763  0.014310  0.148121   
14379  0.014152 -0.019449  0.031402  ... -0.04763  0.030277  0.281666   

          147_x     266_y     0.1.1      17.1      58_y  part_nm_2     107_y  
0      0.024905  0.013744  0.132897 -0.015716 -0.011795  -0.069835 -0.019156  
1     -0.015858  0.017556  0.093069 -0.013386 -0.019042  -0.223262 -0.001482  
2      0.023651 -0.016066  0.024284 -0.086231  0.022743  -0.064022  0.035779  
3      0.008886  0.031605  0.057264 -0.022172  0.071628  -1.814404  0.144794  
4     -0.007116  0.013162  0.074933 -0.010690  0.029209  -0.921132  0.044942  
...         ...       ...       ...       ...       ...        ...       ...  
14375  0.032955  0.059536 -0.016266  0.071283  0.027000  -1.063626 -0.001066  
14376 -0.041499 -0.046940 -0.018725  0.085632  0.101761  -1.814404  0.085759  
14377  0.021205  0.062571  0.171198  0.087243  0.012440  -1.063626  0.021206  
14378  0.006430 -0.019305  0.002525  0.083297 -0.040715   0.284945 -0.002197  
14379  0.050136 -0.025934  0.112632 -0.053286  0.057865  -0.815318 -0.008538  

[14380 rows x 1379 columns]

In [ ]:
cat

custid sales_dayofweek str_nm brd_nm corner_nm   pc_nm  part_nm  \
0           0               일     본점   크리니크   수입종합화장품     화장품     잡화파트   
1           2               수    무역점    노티카     트래디셔널   트래디셔널     가정용품   
2           3               목    천호점   라코스테    골프(LC)    영트랜디   스포츠캐쥬얼   
3           4               목    무역점    시슬리   수입종합화장품  캐릭터캐쥬얼    여성캐주얼   
4           5               목     본점     식품     트래디셔널   트레디셔널  남성정장스포츠   
...       ...             ...    ...    ...       ...     ...      ...   
21582   29995               일    무역점     랑콤   수입종합화장품     장신구     명품잡화   
21583   29996               금    무역점  메트로씨티       핸드백     핸드백     패션잡화   
21584   29997               토    무역점     식품      용기보증    생활용품     잡화파트   
21585   29998               일    무역점    카디날     미확인코너   캐릭터정장     명품잡화   
21586   29999               수    천호점  루이까또즈       핸드백     핸드백       잡화   

      team_nm  buyer_nm  
0       잡화가용팀       화장품  
1       잡화가용팀  트래디셔널캐주얼  
2       잡화가용팀       스포츠  
3       의류패션팀    캐릭터캐주얼  
4       잡화가용팀       스포츠  
...       ...       ...  
21582   의류패션팀      영캐주얼  
21583   잡화가용팀       피혁B  
21584   잡화가용팀      일반식품  
21585   의류패션팀  트래디셔널캐주얼  
21586   잡화가용팀       피혁B  

[21587 rows x 9 columns]

In [ ]:
train = train.iloc[:,1:]

In [ ]:
test = test.iloc[:,1:]

In [ ]:
train

012.1       012   str_num  buyer_nm_2     143_y      0602   pc_nm_1  \
0      0.258656 -0.401774  1.098612    0.008479  0.059594 -0.772427  0.000022   
1      0.258891 -0.347583  1.098612    0.055183  0.028305 -0.602350 -0.021369   
2      0.260489 -0.017115  1.098612   -0.086416 -0.003134 -0.432272 -0.012007   
3      0.260940  0.103395  0.693147   -0.061537 -0.033140 -0.545657 -0.021149   
4      0.258369 -0.456512  1.386294    0.086695  0.032277 -0.432272  0.069499   
...         ...       ...       ...         ...       ...       ...       ...   
21582  0.259313 -0.260748  1.098612   -0.072648  0.003974  1.268501 -0.045918   
21583  0.254983 -1.113412  0.693147   -0.076272 -0.072966 -0.318888 -0.050059   
21584  0.263636  0.570301  1.098612   -0.035039 -0.010159  0.191345 -0.057731   
21585  0.256832 -0.745471  0.693147   -0.121351 -0.013758 -0.092118 -0.026245   
21586  0.262586  0.362927  0.693147   -0.032362  0.051128 -0.715735 -0.028023   

       mean_dis      96.2      23.1  ...     282_x      76_x      25.2  \
0      0.100000 -0.137325 -0.239323  ... -0.076085  0.060838  0.027759   
1      0.072729 -0.144391 -0.234355  ... -0.021540  0.006874 -0.069798   
2      0.033976 -0.066163 -0.132258  ... -0.029402 -0.016076 -0.057467   
3      0.025000  0.154524 -0.182599  ... -0.017321  0.020015  0.118386   
4      0.067187 -0.074612 -0.183990  ... -0.023230  0.000232  0.051903   
...         ...       ...       ...  ...       ...       ...       ...   
21582  0.041447 -0.111386 -0.249637  ...  0.003502  0.022713 -0.005365   
21583  0.073684 -0.178802 -0.232641  ...  0.003473 -0.008924  0.069215   
21584  0.025000 -0.076926 -0.268267  ...  0.038799  0.002664  0.059381   
21585  0.030769 -0.097181 -0.140900  ... -0.005406 -0.012674  0.053710   
21586  0.050000 -0.218570 -0.057732  ... -0.041621  0.007164 -0.007277   

         비비안스타킹       레지나      16_x     262_y     총쇼핑시간  \
0     -0.173885 -0.052019  0.111904  0.015199 -0.502118   
1     -0.173885 -0.052019  0.059249 -0.017121 -0.548124   
2     -0.173885 -0.052019 -0.011010  0.047978  0.064013   
3     -0.173885 -0.052019  0.063700 -0.092825 -0.767526   
4     -0.173885 -0.052019  0.033415  0.031044  0.103539   
...         ...       ...       ...       ...       ...   
21582 -0.173885 -0.052019  0.072669 -0.000973  1.434664   
21583 -0.173885 -0.052019  0.099007 -0.057865 -0.316799   
21584 -0.173885 -0.052019  0.017683  0.002027 -0.291010   
21585 -0.173885 -0.052019  0.066556  0.027246 -0.508825   
21586 -0.173885 -0.052019  0.040216  0.019292 -0.784277   

       part_pc_size_abbd_vegetable      17.3  
0                              0.0 -0.031459  
1                              0.0 -0.031980  
2                              0.0 -0.078417  
3                              0.0 -0.091817  
4                              0.0 -0.077292  
...                            ...       ...  
21582                          0.0 -0.065464  
21583                          0.0 -0.068661  
21584                          1.0  0.027911  
21585                          0.0 -0.061224  
21586                          0.0  0.066236  

[21587 rows x 1352 columns]

In [ ]:
cat_feq = ['sales_dayofweek','str_nm','brd_nm','corner_nm','pc_nm','part_nm','team_nm','buyer_nm']

In [ ]:
cat

custid sales_dayofweek str_nm brd_nm corner_nm   pc_nm  part_nm  \
0           0               일     본점   크리니크   수입종합화장품     화장품     잡화파트   
1           2               수    무역점    노티카     트래디셔널   트래디셔널     가정용품   
2           3               목    천호점   라코스테    골프(LC)    영트랜디   스포츠캐쥬얼   
3           4               목    무역점    시슬리   수입종합화장품  캐릭터캐쥬얼    여성캐주얼   
4           5               목     본점     식품     트래디셔널   트레디셔널  남성정장스포츠   
...       ...             ...    ...    ...       ...     ...      ...   
21582   29995               일    무역점     랑콤   수입종합화장품     장신구     명품잡화   
21583   29996               금    무역점  메트로씨티       핸드백     핸드백     패션잡화   
21584   29997               토    무역점     식품      용기보증    생활용품     잡화파트   
21585   29998               일    무역점    카디날     미확인코너   캐릭터정장     명품잡화   
21586   29999               수    천호점  루이까또즈       핸드백     핸드백       잡화   

      team_nm  buyer_nm  
0       잡화가용팀       화장품  
1       잡화가용팀  트래디셔널캐주얼  
2       잡화가용팀       스포츠  
3       의류패션팀    캐릭터캐주얼  
4       잡화가용팀       스포츠  
...       ...       ...  
21582   의류패션팀      영캐주얼  
21583   잡화가용팀       피혁B  
21584   잡화가용팀      일반식품  
21585   의류패션팀  트래디셔널캐주얼  
21586   잡화가용팀       피혁B  

[21587 rows x 9 columns]

## Tuning

In [ ]:
import sklearn

In [ ]:
sklearn.metrics.log_loss

<function sklearn.metrics._classification.log_loss>

In [ ]:
cat = cat.iloc[:,1:]
cat_te = cat_te.iloc[:,1:]

In [ ]:
cat

sales_dayofweek str_nm brd_nm corner_nm   pc_nm  part_nm team_nm  \
0                   일     본점   크리니크   수입종합화장품     화장품     잡화파트   잡화가용팀   
1                   수    무역점    노티카     트래디셔널   트래디셔널     가정용품   잡화가용팀   
2                   목    천호점   라코스테    골프(LC)    영트랜디   스포츠캐쥬얼   잡화가용팀   
3                   목    무역점    시슬리   수입종합화장품  캐릭터캐쥬얼    여성캐주얼   의류패션팀   
4                   목     본점     식품     트래디셔널   트레디셔널  남성정장스포츠   잡화가용팀   
...               ...    ...    ...       ...     ...      ...     ...   
21582               일    무역점     랑콤   수입종합화장품     장신구     명품잡화   의류패션팀   
21583               금    무역점  메트로씨티       핸드백     핸드백     패션잡화   잡화가용팀   
21584               토    무역점     식품      용기보증    생활용품     잡화파트   잡화가용팀   
21585               일    무역점    카디날     미확인코너   캐릭터정장     명품잡화   의류패션팀   
21586               수    천호점  루이까또즈       핸드백     핸드백       잡화   잡화가용팀   

       buyer_nm  
0           화장품  
1      트래디셔널캐주얼  
2           스포츠  
3        캐릭터캐주얼  
4           스포츠  
...         ...  
21582      영캐주얼  
21583       피혁B  
21584      일반식품  
21585  트래디셔널캐주얼  
21586       피혁B  

[21587 rows x 8 columns]

In [ ]:
train = pd.concat([train,cat],axis=1)
test = pd.concat([test,cat_te],axis=1)

In [ ]:
train.custid

AttributeError: ignored

In [ ]:
# 학습데이터 70%, 평가데이터 30%로 데이터 분할
X_train, X_dev, y_train, y_dev = train_test_split(train, target, test_size=0.3, random_state=0)

In [ ]:
cat_obj = CatBoostClassifier(iterations=100000, task_type = "GPU", learning_rate = 0.01, random_state = 0)
score = model_selection.cross_val_score(cat_obj, X_train, y_train, cv = 5, scoring = 'neg_log_loss')
roc_auc = score.mean()

cat_model = ('CatBoostClassifier', cat_obj, roc_auc)

스트리밍 출력 내용이 길어서 마지막 5000줄이 삭제되었습니다.
0:	learn: 2.0684862	total: 34.2ms	remaining: 2m 51s
1:	learn: 2.0580202	total: 63.6ms	remaining: 2m 38s
2:	learn: 2.0480983	total: 93.2ms	remaining: 2m 35s
3:	learn: 2.0380956	total: 122ms	remaining: 2m 32s
4:	learn: 2.0287299	total: 152ms	remaining: 2m 31s
5:	learn: 2.0195605	total: 180ms	remaining: 2m 30s
6:	learn: 2.0105922	total: 210ms	remaining: 2m 29s
7:	learn: 2.0021586	total: 242ms	remaining: 2m 31s
8:	learn: 1.9941422	total: 274ms	remaining: 2m 31s
9:	learn: 1.9863963	total: 304ms	remaining: 2m 31s
10:	learn: 1.9785273	total: 335ms	remaining: 2m 32s
11:	learn: 1.9709778	total: 366ms	remaining: 2m 32s
12:	learn: 1.9633316	total: 397ms	remaining: 2m 32s
13:	learn: 1.9559182	total: 428ms	remaining: 2m 32s
14:	learn: 1.9485699	total: 458ms	remaining: 2m 32s
15:	learn: 1.9419173	total: 488ms	remaining: 2m 32s
16:	learn: 1.9349881	total: 518ms	remaining: 2m 31s
17:	learn: 1.9281968	total: 549ms	remaining: 2m 31s
18:	learn: 1.9215913	total: 580ms	r

In [ ]:
cat_obj.fit(X_train, y_train, eval_set = (X_dev, y_dev),   early_stopping_rounds = 100)

0:	learn: 2.0685764	test: 2.0686832	best: 2.0686832 (0)	total: 45ms	remaining: 3m 44s
1:	learn: 2.0579546	test: 2.0584157	best: 2.0584157 (1)	total: 81.3ms	remaining: 3m 23s
2:	learn: 2.0474819	test: 2.0481267	best: 2.0481267 (2)	total: 119ms	remaining: 3m 18s
3:	learn: 2.0371571	test: 2.0381836	best: 2.0381836 (3)	total: 177ms	remaining: 3m 41s
4:	learn: 2.0275901	test: 2.0286908	best: 2.0286908 (4)	total: 226ms	remaining: 3m 45s
5:	learn: 2.0182931	test: 2.0196086	best: 2.0196086 (5)	total: 297ms	remaining: 4m 6s
6:	learn: 2.0090904	test: 2.0106344	best: 2.0106344 (6)	total: 397ms	remaining: 4m 43s
7:	learn: 2.0003509	test: 2.0020361	best: 2.0020361 (7)	total: 465ms	remaining: 4m 50s
8:	learn: 1.9921673	test: 1.9940052	best: 1.9940052 (8)	total: 521ms	remaining: 4m 49s
9:	learn: 1.9840517	test: 1.9860682	best: 1.9860682 (9)	total: 572ms	remaining: 4m 45s
10:	learn: 1.9759514	test: 1.9781060	best: 1.9781060 (10)	total: 605ms	remaining: 4m 34s
11:	learn: 1.9683378	test: 1.9706208	best:

In [ ]:
cat_pred = cat_obj.predict_proba(X_dev)

In [ ]:
log_score = sklearn.metrics.log_loss(y_dev, cat_pred)

In [ ]:
log_score

1.4592825232324933

In [ ]:
log_score

1.478600665613553

In [ ]:
log_score

1.4625521586193486

In [ ]:
# test 데이터 평가
preds_class = cat_obj.predict(test)
preds_proba = cat_obj.predict_proba(test)

In [ ]:
print(preds_class)

[['M50']
 ['M40']
 ['F20']
 ...
 ['F20']
 ['F30']
 ['F20']]


In [ ]:
print(preds_proba)

[[0.1283286  0.07720933 0.05717784 ... 0.19002953 0.03024135 0.2396704 ]
 [0.01926781 0.10467824 0.36477928 ... 0.03609698 0.38944399 0.04433399]
 [0.67434865 0.21002686 0.03323483 ... 0.03459093 0.00745552 0.01057959]
 ...
 [0.33883684 0.19954808 0.08419245 ... 0.10829201 0.02385589 0.07727842]
 [0.05790892 0.49719977 0.0762535  ... 0.26427433 0.06329328 0.00690872]
 [0.7796919  0.07979468 0.0262307  ... 0.03686849 0.01191391 0.009382  ]]


In [ ]:
ID_test.custid.unique()

array([30001, 30002, 30003, ..., 49992, 49993, 49994])

In [ ]:
ID_test = ID_test.unique()

AttributeError: ignored

In [ ]:
ID_test

custid
0        30001
1        30001
2        30001
3        30001
4        30001
...        ...
414950   49993
414951   49993
414952   49994
414953   49994
414954   49994

[414955 rows x 1 columns]

In [ ]:
pred = pd.DataFrame(preds_proba)
pred.columns = ['F20', 'F30','F40','F50','M20', 'M30', 'M40', 'M50']
submissions = pd.concat([pd.Series(ID_test.custid.unique(), name = 'ID'), pred], axis = 1)

In [ ]:
submissions

ID       F20       F30       F40       F50       M20       M30  \
0      30001  0.128329  0.077209  0.057178  0.113045  0.164297  0.190030   
1      30002  0.019268  0.104678  0.364779  0.036025  0.005375  0.036097   
2      30003  0.674349  0.210027  0.033235  0.010581  0.019183  0.034591   
3      30005  0.516599  0.110452  0.045334  0.099901  0.026618  0.138323   
4      30007  0.910565  0.041718  0.008751  0.006437  0.017037  0.009940   
...      ...       ...       ...       ...       ...       ...       ...   
14375  49988  0.073977  0.463727  0.076389  0.023673  0.016614  0.222563   
14376  49990  0.369465  0.275063  0.136502  0.055585  0.021219  0.066640   
14377  49992  0.338837  0.199548  0.084192  0.095550  0.072446  0.108292   
14378  49993  0.057909  0.497200  0.076253  0.014190  0.019972  0.264274   
14379  49994  0.779692  0.079795  0.026231  0.010179  0.045940  0.036868   

            M40       M50  
0      0.030241  0.239670  
1      0.389444  0.044334  
2      0.007456  0.010580  
3      0.013280  0.049494  
4      0.002193  0.003359  
...         ...       ...  
14375  0.107890  0.015168  
14376  0.051432  0.024096  
14377  0.023856  0.077278  
14378  0.063293  0.006909  
14379  0.011914  0.009382  

[14380 rows x 9 columns]

In [ ]:
submissions.to_csv('/content/drive/MyDrive/머러컴피티션/2등 features/snd_sum_shap_0612_catsub2.csv', index = False)

In [ ]:
/content/drive/MyDrive/머러컴피티션/2등 features/Snd_scale_modelselect_0612.csv